labels: ["enhancement", "idea"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Idea

        Have an idea for improving our libraries? We'd love to hear it!

  - type: dropdown
    id: language
    attributes:
      label: Related to Language
      description: Which language is this idea for? (Optional - select if language-specific)
      options:
        - "General (all languages)"
        - C#
        - Go
        - Python
        - Java
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Related to Platform
      description: Which MetaTrader version? (Optional - select if platform-specific)
      options:
        - "Both MT4 and MT5"
        - MT4
        - MT5
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this solve? Or what use case does it enable?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?
      placeholder: Other solutions you've thought about

  - type: textarea
    id: example
    attributes:
      label: Code Example
      description: Show how you'd like to use this feature (pseudocode is fine)
      placeholder: |
        ```csharp
        // Example of how this would be used
        ```

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched existing ideas and issues
          required: true
        - label: This idea would benefit other users, not just my specific use case
          required: false
