labels: ["showcase"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🎉 Show and Tell

        Show us what you've built! We love seeing community projects and trading strategies.

  - type: dropdown
    id: language
    attributes:
      label: Programming Language
      description: Which language did you use?
      options:
        - C#
        - Go
        - Python
        - Java
        - Multiple languages
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: MetaTrader Platform
      description: Which platform does your project target?
      options:
        - MT4
        - MT5
        - Both MT4 and MT5
    validations:
      required: true

  - type: textarea
    id: project
    attributes:
      label: Project Description
      description: Tell us about your project
      placeholder: What did you build?
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Key Features
      description: What does your project do?
      placeholder: |
        - Feature 1
        - Feature 2
        - Feature 3

  - type: textarea
    id: tech
    attributes:
      label: Technical Details
      description: What features/libraries did you use? How did you implement it?
      placeholder: |
        - Used gateway for...
        - Implemented trading strategy using...
        - Custom solution for...

  - type: textarea
    id: code
    attributes:
      label: Code Snippets
      description: Share interesting code snippets (optional)
      placeholder: |
        ```csharp
        // Interesting parts of your implementation
        ```

  - type: input
    id: repo
    attributes:
      label: Repository / Link
      description: Link to your project (if public)
      placeholder: https://github.com/...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Demo
      description: Drag and drop images or add links to demos

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've removed any sensitive trading data or credentials
          required: true
